### ISSUE TITLE
indexing error

### ISSUE THREAD

**Issue by gengyanlei** [severian42/GraphRAG-Ollama-UI#23]
win10

Traceback (most recent call last):

  File "E:\Code\Python_Code\chatweb\condaenv\lib\runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "E:\Code\Python_Code\chatweb\condaenv\lib\runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "E:\Code\Python_Code\chatweb\GraphRAG-Ollama-UI\graphrag\index\__main__.py", line 76, in <module>

    index_cli(

  File "E:\Code\Python_Code\chatweb\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 97, in index_cli

    pipeline_config: str | PipelineConfig = config or _create_default_config(

  File "E:\Code\Python_Code\chatweb\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 235, in _create_default_config

    parameters = _read_config_parameters(root, config, reporter)

  File "E:\Code\Python_Code\chatweb\GraphRAG-Ollama-UI\graphrag\index\cli.py", line 269, in _read_config_parameters

    reporter.success(f"Reading settings from {settings_yaml}")

  File "E:\Code\Python_Code\chatweb\GraphRAG-Ollama-UI\graphrag\index\progress\rich.py", line 135, in success

    self._console.print(f"\U0001f680 [green]{message}[/green]")

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\console.py", line 1673, in print

    with self:

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\console.py", line 865, in __exit__

    self._exit_buffer()

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\console.py", line 823, in _exit_buffer

    self._check_buffer()

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\console.py", line 2027, in _check_buffer

    legacy_windows_render(buffer, LegacyWindowsTerm(self.file))

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\_windows_renderer.py", line 19, in legacy_windows_render

    term.write_text(text)

  File "E:\Code\Python_Code\chatweb\condaenv\lib\site-packages\rich\_win32_console.py", line 403, in write_text

    self.write(text)

UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f680' in position 0: illegal multibyte sequence

but this file is Design and Biomimicry_ A Review of Interco - Alice Araujo Marques de Sa.txt.

**Comment by severian42** [comment]
Hey! I don't have a Windows system so this error isn't reproducible on my end. That being said, other users have found a fix by changing the UTF-8 in the system settings [as noted here](https://github.com/severian42/GraphRAG-Ollama-UI/issues/16). Hopefully this helps!

**Comment by gengyanlei** [comment]
tkank you.
